//
// Created by giano on 12/6/18.
//

#ifndef FEEDBACKGENERATOR_REACTIVEFILTERCONTROLLER_H
#define FEEDBACKGENERATOR_REACTIVEFILTERCONTROLLER_H



class ReactiveFilterController {

};



#endif //FEEDBACKGENERATOR_REACTIVEFILTERCONTROLLER_H
